// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as welcomeRouteImport } from "./routes/welcome";
import { Route as waitlistRouteImport } from "./routes/waitlist";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as shellRouteImport } from "./routes/shell";
import { Route as waitlistDotthanksRouteImport } from "./routes/waitlist.thanks";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as workflowsRouteImport } from "./routes/workflows";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as remindersRouteImport } from "./routes/reminders";
import { Route as pulseRouteImport } from "./routes/pulse";
import { Route as projectsRouteImport } from "./routes/projects";
import { Route as homeRouteImport } from "./routes/home";
import { Route as forumRouteImport } from "./routes/forum";
import { Route as cRouteImport } from "./routes/c";
import { Route as browseRouteImport } from "./routes/browse";
import { Route as agentsRouteImport } from "./routes/agents";
import { Route as indexRouteImport } from "./routes/index";
import { Route as workflowsDotworkflowIdRouteImport } from "./routes/workflows.$workflowId";
import { Route as projectsDotprojectIdRouteImport } from "./routes/projects.$projectId";
import { Route as chatDotchannelIdRouteImport } from "./routes/chat.$channelId";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const welcomeRoute = welcomeRouteImport.update({
  id: "/welcome",
  path: "/welcome",
  getParentRoute: () => rootRouteImport,
} as any);
const waitlistRoute = waitlistRouteImport.update({
  id: "/waitlist",
  path: "/waitlist",
  getParentRoute: () => rootRouteImport,
} as any);
const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const shellRoute = shellRouteImport.update({
  id: "/_shell",
  getParentRoute: () => rootRouteImport,
} as any);
const waitlistDotthanksRoute = waitlistDotthanksRouteImport.update({
  id: "/waitlist/thanks",
  path: "/waitlist/thanks",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const workflowsRoute = workflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => shellRoute,
} as any);
const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => shellRoute,
} as any);
const remindersRoute = remindersRouteImport.update({
  id: "/reminders",
  path: "/reminders",
  getParentRoute: () => shellRoute,
} as any);
const pulseRoute = pulseRouteImport.update({
  id: "/pulse",
  path: "/pulse",
  getParentRoute: () => shellRoute,
} as any);
const projectsRoute = projectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => shellRoute,
} as any);
const homeRoute = homeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => shellRoute,
} as any);
const forumRoute = forumRouteImport.update({
  id: "/forum",
  path: "/forum",
  getParentRoute: () => shellRoute,
} as any);
const cRoute = cRouteImport.update({
  id: "/c",
  path: "/c",
  getParentRoute: () => shellRoute,
} as any);
const browseRoute = browseRouteImport.update({
  id: "/browse",
  path: "/browse",
  getParentRoute: () => shellRoute,
} as any);
const agentsRoute = agentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => shellRoute,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => shellRoute,
} as any);
const workflowsDotworkflowIdRoute = workflowsDotworkflowIdRouteImport.update({
  id: "/workflows/$workflowId",
  path: "/workflows/$workflowId",
  getParentRoute: () => shellRoute,
} as any);
const projectsDotprojectIdRoute = projectsDotprojectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => shellRoute,
} as any);
const chatDotchannelIdRoute = chatDotchannelIdRouteImport.update({
  id: "/c/$channelId",
  path: "/c/$channelId",
  getParentRoute: () => shellRoute,
} as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
  "/waitlist": typeof waitlistRoute;
  "/welcome": typeof welcomeRoute;
  "/agents": typeof agentsRoute;
  "/browse": typeof browseRoute;
  "/c": typeof cRoute;
  "/forum": typeof forumRoute;
  "/home": typeof homeRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/waitlist/thanks": typeof waitlistDotthanksRoute;
  "/c/$channelId": typeof chatDotchannelIdRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/repos": typeof reposRoute;
  "/waitlist": typeof waitlistRoute;
  "/welcome": typeof welcomeRoute;
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/browse": typeof browseRoute;
  "/c": typeof cRoute;
  "/forum": typeof forumRoute;
  "/home": typeof homeRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/waitlist/thanks": typeof waitlistDotthanksRoute;
  "/c/$channelId": typeof chatDotchannelIdRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_shell": typeof shellRouteWithChildren;
  "/repos": typeof reposRoute;
  "/waitlist": typeof waitlistRoute;
  "/welcome": typeof welcomeRoute;
  "/_shell/": typeof indexRoute;
  "/_shell/agents": typeof agentsRoute;
  "/_shell/browse": typeof browseRoute;
  "/_shell/c": typeof cRoute;
  "/_shell/forum": typeof forumRoute;
  "/_shell/home": typeof homeRoute;
  "/_shell/projects": typeof projectsRoute;
  "/_shell/pulse": typeof pulseRoute;
  "/_shell/reminders": typeof remindersRoute;
  "/_shell/settings": typeof settingsRoute;
  "/_shell/workflows": typeof workflowsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/waitlist/thanks": typeof waitlistDotthanksRoute;
  "/_shell/c/$channelId": typeof chatDotchannelIdRoute;
  "/_shell/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/_shell/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/repos"
    | "/waitlist"
    | "/welcome"
    | "/agents"
    | "/browse"
    | "/c"
    | "/forum"
    | "/home"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/workflows"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/waitlist/thanks"
    | "/c/$channelId"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/repos"
    | "/waitlist"
    | "/welcome"
    | "/"
    | "/agents"
    | "/browse"
    | "/c"
    | "/forum"
    | "/home"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/workflows"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/waitlist/thanks"
    | "/c/$channelId"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/_shell"
    | "/repos"
    | "/waitlist"
    | "/welcome"
    | "/_shell/"
    | "/_shell/agents"
    | "/_shell/browse"
    | "/_shell/c"
    | "/_shell/forum"
    | "/_shell/home"
    | "/_shell/projects"
    | "/_shell/pulse"
    | "/_shell/reminders"
    | "/_shell/settings"
    | "/_shell/workflows"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/waitlist/thanks"
    | "/_shell/c/$channelId"
    | "/_shell/projects/$projectId"
    | "/_shell/workflows/$workflowId"
    | "/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  shellRoute: typeof shellRouteWithChildren;
  reposRoute: typeof reposRoute;
  waitlistRoute: typeof waitlistRoute;
  welcomeRoute: typeof welcomeRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  waitlistDotthanksRoute: typeof waitlistDotthanksRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/welcome": {
      id: "/welcome";
      path: "/welcome";
      fullPath: "/welcome";
      preLoaderRoute: typeof welcomeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/waitlist": {
      id: "/waitlist";
      path: "/waitlist";
      fullPath: "/waitlist";
      preLoaderRoute: typeof waitlistRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_shell": {
      id: "/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof shellRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/waitlist/thanks": {
      id: "/waitlist/thanks";
      path: "/waitlist/thanks";
      fullPath: "/waitlist/thanks";
      preLoaderRoute: typeof waitlistDotthanksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_shell/workflows": {
      id: "/_shell/workflows";
      path: "/workflows";
      fullPath: "/workflows";
      preLoaderRoute: typeof workflowsRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/settings": {
      id: "/_shell/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/reminders": {
      id: "/_shell/reminders";
      path: "/reminders";
      fullPath: "/reminders";
      preLoaderRoute: typeof remindersRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/pulse": {
      id: "/_shell/pulse";
      path: "/pulse";
      fullPath: "/pulse";
      preLoaderRoute: typeof pulseRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/projects": {
      id: "/_shell/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof projectsRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/home": {
      id: "/_shell/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof homeRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/forum": {
      id: "/_shell/forum";
      path: "/forum";
      fullPath: "/forum";
      preLoaderRoute: typeof forumRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/c": {
      id: "/_shell/c";
      path: "/c";
      fullPath: "/c";
      preLoaderRoute: typeof cRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/browse": {
      id: "/_shell/browse";
      path: "/browse";
      fullPath: "/browse";
      preLoaderRoute: typeof browseRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/agents": {
      id: "/_shell/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof agentsRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/": {
      id: "/_shell/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/workflows/$workflowId": {
      id: "/_shell/workflows/$workflowId";
      path: "/workflows/$workflowId";
      fullPath: "/workflows/$workflowId";
      preLoaderRoute: typeof workflowsDotworkflowIdRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/projects/$projectId": {
      id: "/_shell/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof projectsDotprojectIdRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/_shell/c/$channelId": {
      id: "/_shell/c/$channelId";
      path: "/c/$channelId";
      fullPath: "/c/$channelId";
      preLoaderRoute: typeof chatDotchannelIdRouteImport;
      parentRoute: typeof shellRoute;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface shellRouteChildren {
  indexRoute: typeof indexRoute;
  agentsRoute: typeof agentsRoute;
  browseRoute: typeof browseRoute;
  cRoute: typeof cRoute;
  forumRoute: typeof forumRoute;
  homeRoute: typeof homeRoute;
  projectsRoute: typeof projectsRoute;
  pulseRoute: typeof pulseRoute;
  remindersRoute: typeof remindersRoute;
  settingsRoute: typeof settingsRoute;
  workflowsRoute: typeof workflowsRoute;
  chatDotchannelIdRoute: typeof chatDotchannelIdRoute;
  projectsDotprojectIdRoute: typeof projectsDotprojectIdRoute;
  workflowsDotworkflowIdRoute: typeof workflowsDotworkflowIdRoute;
}

const shellRouteChildren: shellRouteChildren = {
  indexRoute: indexRoute,
  agentsRoute: agentsRoute,
  browseRoute: browseRoute,
  cRoute: cRoute,
  forumRoute: forumRoute,
  homeRoute: homeRoute,
  projectsRoute: projectsRoute,
  pulseRoute: pulseRoute,
  remindersRoute: remindersRoute,
  settingsRoute: settingsRoute,
  workflowsRoute: workflowsRoute,
  chatDotchannelIdRoute: chatDotchannelIdRoute,
  projectsDotprojectIdRoute: projectsDotprojectIdRoute,
  workflowsDotworkflowIdRoute: workflowsDotworkflowIdRoute,
};

const shellRouteWithChildren = shellRoute._addFileChildren(shellRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  shellRoute: shellRouteWithChildren,
  reposRoute: reposRoute,
  waitlistRoute: waitlistRoute,
  welcomeRoute: welcomeRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  waitlistDotthanksRoute: waitlistDotthanksRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
